config/routes.rb
FirstApp::Application.routes.draw do

devise_for :users, :skip => :registrations

namespace :admin do
  resources :users
end

  get "contacts" => 'contacts#index', :as=>:contacts
  get "get_docfile/:id" => 'docs#get_docfile', :as=>:get_docfile
  get "i_am_superadmin" => 'application#i_am_superadmin'

  resources :clients

  resources :services

  resources :docs do
    get "get_categories", :on=> :collection
  end

  resources :start_articles

  
  root :to => 'start_articles#index'

end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/controllers/services_controller.rb
# encoding: utf-8
class ServicesController < ApplicationController
  before_filter :set_page
  before_filter :is_admin, :except=>:index

  # GET /services
  # GET /services.json
  def index
    @services = Service.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @services }
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @service = Service.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @service }
    end
  end

  # GET /services/new
  # GET /services/new.json
  def new
    @service = Service.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @service }
    end
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(params[:service])

    respond_to do |format|
      if @service.save
        format.html { redirect_to services_path, :notice => 'Service was successfully created.' }
        format.json { render :json => @service, :status => :created, :location => @service }
      else
        format.html { render :action => "new" }
        format.json { render :json => @service.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /services/1
  # PUT /services/1.json
  def update
    @service = Service.find(params[:id])

    respond_to do |format|
      if @service.update_attributes(params[:service])
        format.html { redirect_to services_path, :notice => 'Услуга обновлена' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @service.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url }
      format.json { head :no_content }
    end
  end

  private

  def set_page
    @selected_page=:page2
  end


end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %>, Знайдено помилки при заповненні форми:</h2>

      <ul>
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Послуга' %><br />
    <%= f.text_area :name %>
  </div>

<!--
  <div class="field">
    <  f.label 'Вартість' %><br />
    <  f.text_field :price %>
  </div>
-->

  <div class="actions">
    <%= f.submit 'Застосувати'%>
  </div>
<% end %>

app/views/services/edit.html.erb
<h3>Редагування послуги</h3>

<%= render 'form' %>

<%= link_to 'Назад', services_path %>

app/views/services/index.html.erb
<%= render "layouts/sidebar" %>
<div id="content_ajax">
    
    <h2> Послуги</h2>
    <br/>
    <table class="docs_table">

    <% @services.each do |service| %>
      <tr>
        <td><li><%= simple_format(service.name) %></li></td>
        <%= admin_link_to_td 'Редагувати', edit_service_path(service) %>
        <%= admin_link_to_td 'Видалити', service, :confirm => 'Точно?', :method => :delete %>
      </tr>
    <% end %>
    </table>

    <br />

    <%= admin_link_to 'Додати послугу', new_service_path %>
</div>

app/views/services/new.html.erb
<h1>Нова послуга</h1>

<%= render 'form' %>

<%= link_to 'Назад', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Найменування послуги</b>
  <%= @service.name %>
</p>

<!--
<p>
  <b>Вартість</b>
  < @service.price %>
</p>
-->

<%= link_to 'редагувати', edit_service_path(@service) %> |
<%= link_to 'Назад', services_path %>