config/routes.rb
FirstApp::Application.routes.draw do

devise_for :users, :skip => :registrations

namespace :admin do
  resources :users
end

  get "contacts" => 'contacts#index', :as=>:contacts
  get "get_docfile/:id" => 'docs#get_docfile', :as=>:get_docfile
  get "i_am_superadmin" => 'application#i_am_superadmin'

  resources :clients

  resources :services

  resources :docs do
    get "get_categories", :on=> :collection
  end

  resources :start_articles

  
  root :to => 'start_articles#index'

end

app/models/doc.rb
class Doc < ActiveRecord::Base
  has_attached_file :docfile,
                    :storage=>{
                      ###'development'=>:s3,
                      'development'=>:filesystem,
                      ####'production'=>:s3
		      'production'=>:filesystem
                    }[Rails.env],

                    :url => {
                      ###'development'=> "fyhome/:attachment/:id/:basename.:extension",
                      'development'=> "#{Rails.root}/public/docs-d/:attachment/:id/:basename.:extension",
                      ###'production'=> "heroku/:attachment/:id/:basename.:extension"
		      'production'=> "#{Rails.root}/public/docs-p/:attachment/:id/:basename.:extension",
                    }[Rails.env],


                    :path => {
                      ###'development'=> "fyhome/:attachment/:id/:basename.:extension",
                      'development'=> "#{Rails.root}/public/docs-d/:attachment/:id/:basename.:extension",
                      'production'=> "#{Rails.root}/public/docs-p/:attachment/:id/:basename.:extension"
                    }[Rails.env]
#		    ,
#                    :bucket         => ENV['S3_BUCKET'],
#                    :s3_credentials => { :access_key_id     => ENV['S3_KEY'],
#                                         :secret_access_key => ENV['S3_SECRET']}

  validates_attachment_size :docfile, :less_than => 10.megabytes
  validates :content, :presence=> true


end

app/controllers/docs_controller.rb
# encoding: utf-8
class DocsController < ApplicationController
  before_filter :set_page
  before_filter :is_admin, :except=>[:index, :get_docfile, :get_categories]

  ###
  respond_to :html, :json, :js
  

  def get_docfile
    doc=Doc.find(params[:id])
    case Rails.env
    when 'development'
      send_file doc.docfile.path
      ### redirect_to URI.encode(::FILE_SERV+doc.docfile.path)
    when 'production'
      send_file doc.docfile.path
      ### redirect_to URI.encode(::FILE_SERV+doc.docfile.path)    
    end
  end

  # GET /docs
  # GET /docs.json

  def index
    params[:category]&&params[:category]!='' ?  @docs = Doc.find_all_by_content(params[:category]) : @docs = Doc.all
    respond_with @docs
  end

  def get_categories
    @categories = Doc.select(:content).uniq.all
    respond_with @categories
  end

  # GET /docs/1
  # GET /docs/1.json
  def show
    @doc = Doc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @doc }
    end
  end

  # GET /docs/new
  # GET /docs/new.json
  def new
    @doc = Doc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @doc }
    end
  end

  # GET /docs/1/edit
  def edit
    @doc = Doc.find(params[:id])
  end

  # POST /docs
  # POST /docs.json
  def create
    @doc = Doc.new(params[:doc])

    respond_to do |format|
      if @doc.save
        format.html { redirect_to @doc, :notice => 'Документ создан' }
        format.json { render :json => @doc, :status => :created, :location => @doc }
      else
        format.html { render :action => "new" }
        format.json { render :json => @doc.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /docs/1
  # PUT /docs/1.json
  def update
    @doc = Doc.find(params[:id])

    respond_to do |format|
      if @doc.update_attributes(params[:doc])
        format.html { redirect_to docs_path, :notice => 'Документ обновлён' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @doc.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /docs/1
  # DELETE /docs/1.json
  def destroy
    @doc = Doc.find(params[:id])
    @doc.destroy

    respond_to do |format|
      format.html { redirect_to docs_url }
      format.json { head :no_content }
    end
  end

  private

  def set_page
    @selected_page=2
  end

  private

  def set_page
    @selected_page=:page3
  end


end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/docs/_content.erb
<div id="content">
  <h2>Документи</h2>
  <br/>
  <table class="docs_table">
    <tr>
      <th>Назва</th>
      <th>Категорія</th>
      <th>файл:</th>
      <th></th>
      <th></th>
    </tr>
  <% @docs.each do |doc| %>
    <tr>
      <td><%= doc.name %></td>
      <td><%= doc.content %></td>
      <td><%= link_to doc.docfile_file_name, get_docfile_path(doc.id)  %></td>
      <%= admin_link_to_td 'Редагувати', edit_doc_path(doc) %>
      <%= admin_link_to_td 'Видалити', doc, :confirm => 'Точно?', :method => :delete %>
    </tr>
  <% end %>
  </table>

  <br />

  <%= admin_link_to 'Додати документ', new_doc_path %>
</div>

app/views/docs/_form.html.erb
<%= form_for @doc, :html => { :multipart => true } do |f| %>
  <% if @doc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doc.errors.count, "error") %> prohibited this doc from being saved:</h2>

      <ul>
      <% @doc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br/>
  <div class="field">
    <%= f.label "Назва" %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label "Категорія" %><br />
    <%= f.text_field :content %>
  </div>


  <div class="field">
    <%= f.label "файл:"%><br />
    <%= f.file_field :docfile %>
  </div>


  <div class="actions">
    <br/>
    <%= f.submit 'Застосувати'%>
  </div>
<% end %>

app/views/docs/_sidebar.erb
<div id="sidebar_doc">
  <div id="user_nav">

    <% if notice or alert %>
      <p class="notice"> <%= notice%></p>
      <p class="alert"> <%= alert%></p>
    <% end %>

  </div>

<h4>Документи за категоріями:</h4>
<div id="doctree"></div>

</div>

app/views/docs/edit.html.erb
<h2>Редагування документа</h2>

<%= render 'form' %>
<br/>
<%= link_to 'Назад до списка документів', docs_path %>

app/views/docs/index.html.erb
<%= render "sidebar" %>
<%= render "content" %>

app/views/docs/index.js.erb
$('#content').html("<%= escape_javascript render('content') %>")

app/views/docs/new.html.erb
<h1>Новий документ</h1>

<%= render 'form' %>

<%= link_to 'назад', docs_path %>

app/views/docs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Назва:</b>
  <%= @doc.name %>
</p>

<p>
  <b>Категорія:</b>
  <%= @doc.content %>
</p>


<%= link_to 'Редагувати', edit_doc_path(@doc) %> |
<%= link_to 'Назад', docs_path %>