config/routes.rb
FirstApp::Application.routes.draw do

devise_for :users, :skip => :registrations

namespace :admin do
  resources :users
end

  get "contacts" => 'contacts#index', :as=>:contacts
  get "get_docfile/:id" => 'docs#get_docfile', :as=>:get_docfile
  get "i_am_superadmin" => 'application#i_am_superadmin'

  resources :clients

  resources :services

  resources :docs do
    get "get_categories", :on=> :collection
  end

  resources :start_articles

  
  root :to => 'start_articles#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin

  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate_user! #, except => [:load_user] #, :only => [:index]
 # before_filter :load_user
  
  #def index
  #  @users=User.all
  #end

  def index
    @users = User.where("id NOT IN (?)", current_user.id) # don't display the current user in the users list; go to account management to edit current user details
  end

  def new
    @user=User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "#{ @user.email } created."
      redirect_to admin_users_path
    else
      render :action => 'new'
    end
  end

  def edit
    @user=User.find_by_id(params[:id])
    render :new
  end

  def update
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
    if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully updated User."
      redirect_to admin_users_path
    else
      ## render :action => 'edit'
      redirect_to edit_admin_user_path(params)
    end
  end

  def delete
  end

  def destroy
    redirect_to users_path and return if params[:cancel]
    if @user.destroy
      flash[:notice] = "#{ @user.email } deleted."
      redirect_to admin_users_path
    end
  end

  def show
    @user = User.find(params[:id])
  end


  private
  
#  def load_user
#    @user=User.find(params[:id]) if params[:id]
#  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<div id="content">

    <h2>Користувачі</h2>
    <br/>
    <table>
      <tr>
        <th>email</th>
        <th>in_count</th>
        <th>last_sign_in_at</th>
        <th>last_sign_in_ip</th>
        <th>updated_at</th>
        <th>admin?</th>
      </tr>

    <% @users.each do |u| %>
      <tr>

        <td><%= u.email %></td>
        <td><%= u.sign_in_count %></td>
        <td><%= u.last_sign_in_at %></td>
        <td><%= u.last_sign_in_ip %></td>
        <td><%= u.updated_at %></td>
        <td><%= u.admin %></td>


        <td><%= admin_link_to 'Редагувати', edit_admin_user_path(u) %></td>
        <td><%= admin_link_to 'Видалити', admin_user_path(u), :confirm => 'Точно?', :method=> :delete %></td>
      </tr>
    <% end %>
    </table>

    <br />

    <%= admin_link_to 'Додати користувача', new_admin_user_path %>
</div>

<%= render "layouts/sidebar" %>

app/views/admin/users/new.html.erb
<h2>Новый пользователь</h2>
<br/>
<%= form_for(@user, :url => admin_users_path(@user)) do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div><%= f.label 'E-mail:' %><br />
  <%= f.email_field :email %></div>

  <div><%= f.label 'Пароль:' %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label 'Подтверждение пароля:' %><br />
  <%= f.password_field :password_confirmation %></div>

  <% if current_user&&current_user.admin? %>
    <div>  <%= f.check_box :admin %> <%= f.label 'Администратор?' %></div>
  <% end %>

  <br />
  <div><%= f.submit "Сохранить" %></div>
<% end %>

<br />