config/routes.rb
FirstApp::Application.routes.draw do

devise_for :users, :skip => :registrations

namespace :admin do
  resources :users
end

  get "contacts" => 'contacts#index', :as=>:contacts
  get "get_docfile/:id" => 'docs#get_docfile', :as=>:get_docfile
  get "i_am_superadmin" => 'application#i_am_superadmin'

  resources :clients

  resources :services

  resources :docs do
    get "get_categories", :on=> :collection
  end

  resources :start_articles

  
  root :to => 'start_articles#index'

end

app/views/layouts/_sidebar.erb
<div id="sidebar">
  <div id="user_nav">
    <% if user_signed_in? %>
      <h4>Ви зайшли на сайт як <%= current_user.email %></h4>
      <p><%= link_to "Вийти", destroy_user_session_path, :method => :delete %></p>
      <p><%= link_to "Редагувати профіль", edit_admin_user_path( current_user.id ) %></p>
      <p><%= link_to "Новий користувач", new_admin_user_path %></p>
      <p><%= link_to "Перелік користувачів", admin_users_path %></p>
    <% end %>
  </div>

</div>

app/views/layouts/_test_login_info.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Столичний реєстратор</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>


<body>
<div id="wrapper">
	<div id="header">
		<div id="menu">
			<ul>
                                <%= li_current_page_item(@selected_page, :page1 ) do %>
                                    <%=  link_to "Про компанію", start_articles_url%>
                                <%  end %>

                                <%= li_current_page_item(@selected_page, :page2 ) do %>
                                    <%=  link_to "Функції", services_url%>
                                <%  end %>

                                <%= li_current_page_item(@selected_page, :page3 ) do %>
                                    <%=  link_to "Документи", docs_url%>
                                <%  end %>
<!--
                                <= li_current_page_item(@selected_page, :page4 ) do %>
                                    <=  link_to "Клиенты", clients_url%>
                                <  end %>
-->
                                <%= li_current_page_item(@selected_page, :page5 ) do %>
                                    <%=  link_to "Контакти", contacts_url%>
                                <%  end %>
			</ul>
		</div>
		<!-- end #menu -->
	</div>
	<div id="logo">
		<h1><%=  link_to 'Столичний реєстратор', root_path %></h1>
                <p><em> ТОВ "Столичний реєстратор" </em></p>
		<p><em> Учасник Фондового ринку України </em></p>
	</div>
	<hr />
	<!-- end #logo -->



	<div id="page">

                <%= yield %>
          	<div style="clear: both;">&nbsp;</div>
          
	</div>
	<!-- end #page -->

        <div id="footer">
          <%= link_to "Вхід", new_user_session_path %>


		<p>Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>
	</div>
	<!-- end #footer -->
</div>
</body>


</html>